### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by niladam** [djurovicigoor/lara-files#4]
hi @djurovicigoor - i think you should tag a new release that contains the latest changes :)

**Comment by djurovicigoor** [comment]
I was planning to add support for Amazon web s3 by tomorrow night and after that to tag a new release. But I can add a new tag now if you want.

**Comment by niladam** [comment]
@djurovicigoor you could have waited until then if that was the case. It was only a suggestion, i'm not deciding on what you do with your package :)

Adding support for S3 sounds really good and i'm sure people will appreciate it!:)

Keep it up!:)

**Comment by djurovicigoor** [comment]
@niladam It's not a big deal to tag a new release now :) 
Me to. Alongside S3 I'm planning to add support for other cloud systems as a Dropbox and Google Drive in the future.

**Comment by niladam** [comment]
You're hard at work i see! Good job buddy!:)

**Comment by djurovicigoor** [comment]
Thank you, that's in my blood! : D
I used a lot of good things from the community, it's time to return as much as I can. :)
